# -*- coding: utf-8 -*-
"""Assignment-2 Practical-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16HuHEjMOKzEQgIjiGab-nuP24tzxxdLP
"""

#Practical-1
#Opning files "Input.txt" and "Output.txt" in "r" and "w" mode respectively
file1 = open("Input.txt","r")
file2 = open("Output.txt","w")
#reading file 
for i in range(1,7):
  f = file1.readline()
  x=f.split(" ")

  if x[0]=="ADD":#checking if the function performed is Addition
    add=0
    for i in range(1,len(x)): #getting data from the line
     add = int(add)+int(x[i]) #adding

    print(add)
    file2.write("Add %d"%(add))


  elif(x[0])=="SUB": #checking if the function performed is Subtraction
    sub = int(x[1])
    for i in range(2,len(x)): #getting data from the line
      sub = int(sub)-int(x[i]) #Subtracting
      print(sub)
    file2.write("Sub %d"%(sub))


  elif(x[0])=="MUL": #checking if the function performed is multiplication
    product=1
    for i in range(1,len(x)): #getting data from the line
      product = int(product)*int(x[i]) #Multiplying
    print(product)
    file2.write("Mul %d"%(product))


  elif(x[0])=="POW":#checking if the function performed is power
    pow = 1
    file2.write("Pow ")
    for i in range(1,len(x),2): #getting data from the line
      pow = int(x[i])**int(x[i+1]) #Raised to operation
      file2.write("%d\t"%(pow))


  elif (x[0]=="DIV"): #checking if the function performed is division
    dividend=int(x[1])
    for i in range(2,len(x)): #getting data from the line
      dividend = int(dividend)/int(x[i]) #Division
    print(dividend)
    file2.write("Div %d"%dividend)


  elif(x[0]=="MOD"): #checking if the function performed is modulud
      mod=0
      file2.write("Mod ")
      for i in range(1,len(x),2): #getting data from the line
        mod = int(x[i])%int(x[i+1]) #Modulus
        file2.write("%d\t"%(mod)) 
#closing files
file2.close()
file1.close()