# -*- coding: utf-8 -*-
"""Assignment-2 Practical-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_cGm6OnQS0hh1TxenWFvVkz4roHlGJWH
"""

#Practical-2
#Opning files "Input.txt" and "Output.txt" in "r" and "w" mode respectivel
file1 = open("Input.txt","r")
file2 = open("Output.txt","w")
#declaring and initializaing variables
name=""
fail=0
total=0
large=0
s=0

for i in range(0,7): #reading inputs from file

  f=file1.readline()
  x = f.split(",")
  #print(x)

  if x[0] == "Name": #Looking for required data
    continue

  else:
    total = total+1 
    s=0
    
    for j in range(1,len(x)): #Looking for marks of a student
      s = int(s)+int(x[j]) #Taking sum of scores 
     
      if int(x[j])<40:  #Checcking the passing criteria
        fail+=1
        break
    if(s>large): #Updating highest score
      large = s
#writing in file
file2.write(f"Student with first class is:{name}\n")
file2.write("Number of students fully passed:%d\n"%(total-fail))
file2.write("Number of students failed:%d\n"%(fail))
#closing files
file1.close()
file2.close()