# -*- coding: utf-8 -*-
"""My Fruit Shop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZfBYrlCIx-DphU3w-vHWzHMwcZC4ZlwP
"""

from google.colab import output
stock = {}
sell = {}
history = {}
profit_percent=10

print("*****Welcome to stock management system*****")
print("1->Buy")
print("2->Sell")
print("3->Stock")
print("4->Exit")
choice=int(input("Enter choice:"))

while choice>0 and choice<5:
  if choice==1:

    output.clear()
    fruit=input("Enter fruit to be purchased:")
    if fruit in stock:
      quantity = int(input("Please enter quantity of "+fruit+" you want to purchase:"))
      stock[fruit] += quantity
      temp=history[fruit]
      purchase_price = history[fruit]+(temp*0.05)
      amount_payable = quantity*purchase_price
      print("********My Fruit Shop********")
      print("Total amount payable:",amount_payable)
      print("Thank you for shopping with us")
      print("______________________________")
      selling_price=purchase_price*profit_percent/100
      sell[fruit] = selling_price + purchase_price
      print(stock)
      print(sell)
      print()
      print("*****Welcome to stock management system*****")
      print("1->Buy")
      print("2->Sell")
      print("3->Stock")
      print( "4->Exit")
      choice=int(input("Enter choice:"))
    else:
      quantity = int(input("Please enter quantity of "+fruit+" you want to purchase:"))
      stock[fruit] = quantity
      print(stock)
      purchase_price=float(input("Please enter purchse price per kg:"))
      history[fruit] = purchase_price
      amount_payable = quantity*purchase_price
      print("********My Fruit Shop********")
      print("Total amount payable:",quantity*purchase_price)
      print("Thank you for shopping with us")
      print("______________________________")
      print()
      selling_price=purchase_price*profit_percent/100
      sell[fruit] = selling_price + purchase_price
      print(stock)
      print(sell)
      print("*****Welcome to stock management system*****")
      print("1->Buy")
      print("2->Sell")
      print("3->Stock")
      print( "4->Exit")
      choice=int(input("Enter choice:"))


  elif choice == 2:
    output.clear()
    fruit = input("Enter fruit you want to purchase:")
    if fruit in sell:
      quantity = float(input("Please enter quantity of "+fruit+" you want to purchase:"))
      if stock[fruit]>=quantity:
        print("********My Fruit Shop********")
        print("Total amount payable:",quantity*sell[fruit])
        print("Thank you for shopping with us")
        print("______________________________")
        print()
        stock[fruit]-=quantity
        print(stock)
        print(sell)
        print("*****Welcome to stock management system*****")
        print("1->Buy")
        print("2->Sell")
        print("3->Stock")
        print( "4->Exit")
        choice=int(input("Enter choice:"))

      else:
        print("We have "+str(stock[fruit])+"kg of "+ fruit+".")
        print("Do you want to purchase "+str(stock[fruit])+"kg:")
        option = input("Y/n:")
        if option == "Y" or option == "y":
          print("********My Fruit Shop********")
          print("Total amount payable:",quantity*sell[fruit])
          print("Thank you for shopping with us")
          print("______________________________")
          print()
          stock[fruit]=0
          print(stock)
          print(sell)
          print("*****Welcome to stock management system*****")
          print("1->Buy")
          print("2->Sell")
          print("3->Stock")
          print( "4->Exit")
          choice=int(input("Enter choice:"))

        elif option == "n" or option == "N":
          print("Please try buying something rom below displayed fruits")
          print(stock)
          print("*****Welcome to stock management system*****")
          print("1->Buy")
          print("2->Sell")
          print("3->Stock")
          print( "4->Exit")
          choice=int(input("Enter choice:"))
    else:
      print("Currently we are not available with "+ fruit +" in our shop")
      print("Please try buying something rom below displayed fruits")
      print(stock)
      print("*****Welcome to stock management system*****")
      print("1->Buy")
      print("2->Sell")
      print("3->Stock")
      print( "4->Exit")
      choice=int(input("Enter choice:"))


  elif choice == 3:
    output.clear()
    print("****Stock Summary****")
    if stock == {}:
      print("Please buy some fruits first... Your basket is empty")
      print("1->Buy")
      print("2->Sell")
      print("3->Stock")
      print( "4->Exit")
      choice=int(input("Enter choice:"))
    else:
      print(stock)
      print()
      print("1->Buy")
      print("2->Sell")
      print("3->Stock")
      print( "4->Exit")
      choice=int(input("Enter choice:"))


  elif choice == 4:
    print("Thank you for shopping with us")
    break

