# -*- coding: utf-8 -*-
"""Practice 21-05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vhy3EPCqrpN62xgZGZZVTs_J9d_BkhpM
"""

#Task-1:Print All record in OUTPUT.txt.

'''
#opening file Input in "w" mode
input_file = open("Input.txt","w")
input_file.write("Student Name , Sub1 , Sub2 , Sub3\n"
                  "Virat Kohli, 70, 56, 45\n"
                  "Suresh Raina, 80,28, 39\n"
                  "Yuvraj Singh, 69, 40,25\n"
                  "MS Dhoni,12, 15,17\n"
                  "Rohit Sharma,97,90,79\n"
                  "Shikhar Dhawan,66, 90,90\n"
                  "Rahul Dravid, 40, 58, 59\n"
)
input_file.close()
'''
#opening file Input in "r" mode and Output in "w" mode
input_file = open("Input.txt","r")
output_file = open("Output.txt","w")
data = input_file.read() #reading data
output_file.write(data) #writing data 

#Closing files
input_file.close()
output_file.close()

#this program complied and ran successfully

#Task-2:Print All record in OUTPUT.txt.

'''
#opening file Input in "w" mode
input_file = open("Input.txt","w")
input_file.write("Student Name , Sub1 , Sub2 , Sub3\n"
                  "Virat Kohli, 70, 56, 45\n"
                  "Suresh Raina, 80,28, 39\n"
                  "Yuvraj Singh, 69, 40,25\n"
                  "MS Dhoni,12, 15,17\n"
                  "Rohit Sharma,97,90,79\n"
                  "Shikhar Dhawan,66, 90,90\n"
                  "Rahul Dravid, 40, 58, 59\n"
)
input_file.close()
'''

#opening file Input in "r" mode and Output in "w" mode
input_file = open("Input.txt","r")
output_file = open("Output.txt","w")

data = input_file.readlines() #reading data from file using readline()
output_file.writelines(data)  #writing data from file using readline()

 #closing files
input_file.close()   
output_file.close()

#this program complied and ran successfully

#Task-3:Copy Virat Kohli’s record into Output.txt.
'''
#opening file Input in "w" mode
input_file = open("Input.txt","w")
input_file.write("Student Name , Sub1 , Sub2 , Sub3\n"
                  "Virat Kohli, 70, 56, 45\n"
                  "Suresh Raina, 80,28, 39\n"
                  "Yuvraj Singh, 69, 40,25\n"
                  "MS Dhoni,12, 15,17\n"
                  "Rohit Sharma,97,90,79\n"
                  "Shikhar Dhawan,66, 90,90\n"
                  "Rahul Dravid, 40, 58, 59\n"
)
input_file.close()
'''

#opening file Input in "r" mode and Output in "w" mode
input_file = open("Input.txt","r")
output_file = open("Output.txt","w")
data1 = input_file.readlines(35) #readlines() takes integer argument which specifies number of bytes to be read by the function
virat = data1[1]   #extracting Virat's data 
output_file.write(virat) #writing virat's data in file
#closing files
input_file.close()
output_file.close()

#this program complied and ran successfully

#Task:4:Copy Virat Kohli's record with total marks into Output.txt.
'''
#opening file Input in "w" mode
input_file = open("Input.txt","w")
input_file.write("Student Name , Sub1 , Sub2 , Sub3\n"
                  "Virat Kohli, 70, 56, 45\n"
                  "Suresh Raina, 80,28, 39\n"
                  "Yuvraj Singh, 69, 40,25\n"
                  "MS Dhoni,12, 15,17\n"
                  "Rohit Sharma,97,90,79\n"
                  "Shikhar Dhawan,66, 90,90\n"
                  "Rahul Dravid, 40, 58, 59\n"
)
input_file.close()
'''
#opening file Input in "r" mode and Output in "w" mode
input_file = open("Input.txt","r")
output_file = open("Output.txt","w")
data1 = input_file.readlines(35) #readlines() takes integer argument which specifies number of bytes to be read by the function
virat = data1[1]   #extracting Virat's data
output_file.write(virat) #writing virat's data in file
virat = virat.split(",")  #splitting virat's data with ','
sum = int(virat[1])+int(virat[2])+int(virat[3])   #sum of marks
output_file.write(str(sum)) 

#closing files
input_file.close()
output_file.close()

#this program complied and ran successfully

#Task-5:Copy All records with total marks into Output.txt.

#opening file Input in "w" mode
input_file = open("Input.txt","w")
print("Student Name , Sub1 , Sub2 , Sub3",
                  "Virat Kohli, 70, 56, 45",
                  "Suresh Raina, 80,28, 39",
                  "Yuvraj Singh, 69, 40,25",
                  "MS Dhoni,12, 15,17",
                  "Rohit Sharma,97,90,79",
                  "Shikhar Dhawan,66, 90,90",
                  "Rahul Dravid, 40, 58, 59", sep=("\n"), file=input_file
)
input_file.close()
#opening file Input in "r" mode and Output in "w" mode
input_file = open("Input.txt","r")
output_file = open("Output.txt","w")
sum=0
for i in range(0,8):
  sum=0
  data = input_file.readline()
  data1 = data.split(",")

  if data1[0]=="Student Name ":
    continue
  else:
    sum = int(data1[1])+int(data1[2])+int(data1[3])
    sum = str(sum)
    print("{},{},{},{},{}".format(data1[0],data1[1],data1[2],data1[3].rstrip(),sum),file=output_file)

#closing files
input_file.close()
output_file.close()



#this program complied and ran successfully

#Task-6:Check if Virat Kohli pass the exam? IF yes then print his name in output.txt

'''
#opening file Input in "w" mode
input_file = open("Input.txt","w")
input_file.write("Student Name , Sub1 , Sub2 , Sub3\n"
                  "Virat Kohli, 70, 56, 45\n"
                  "Suresh Raina, 80,28, 39\n"
                  "Yuvraj Singh, 69, 40,25\n"
                  "MS Dhoni,12, 15,17\n"
                  "Rohit Sharma,97,90,79\n"
                  "Shikhar Dhawan,66, 90,90\n"
                  "Rahul Dravid, 40, 58, 59\n"
)
input_file.close()
'''
#opening file Input in "r" mode and Output in "w" mode
input_file = open("Input.txt","r")
output_file = open("Output.txt","w")
count=0     #this counter will take care of whether he passes in all three subjects or not
data = input_file.readlines(35) #reading first twom lines of file
virat =data[1] #extracting Virat's data
virat = virat.split(",") #splitting Virat's data using ',' separator
for i in range(1,4):
  if int(virat[i])<40:  #checking if he failed in that particular subject or not
    break
  else:
    count+=1    #if not then counter ++
if count==3:
  output_file.write(virat[0]) #if passed in all three subjects then writing his nama in file
#closing files
  input_file.close()
  output_file.close()

#this program complied and ran successfully

#Task-7 Write Name of all Students in Output.txt who cleared exam
'''
#opening file Input in "w" mode
input_file = open("Input.txt","w")
input_file.write("Student Name , Sub1 , Sub2 , Sub3\n"
                  "Virat Kohli, 70, 56, 45\n"
                  "Suresh Raina, 80,28, 39\n"
                  "Yuvraj Singh, 69, 40,25\n"
                  "MS Dhoni,12, 15,17\n"
                  "Rohit Sharma,97,90,79\n"
                  "Shikhar Dhawan,66, 90,90\n"
                  "Rahul Dravid, 40, 58, 59\n"
)
input_file.close()
'''
#opening file Input in "r" mode and Output in "w" mode
input_file = open("Input.txt","r")
output_file = open("Output.txt","w")
flag=0


for i in range(0,8):
  data =  input_file.readline()
  data1 = data.split(",")
  flag=0
  if data1[0] == "Student Name ":
    continue

  else:
    for j in range(1,4):
      if int(data1[j])<=40:
        break
      else:
        flag+=1
  if flag==3:
    output_file.write("Virat Kohli+"\n")

#this program complied and ran successfully

#Task-8 Find How many Students Cleared Exam? Write No of Pass and Fail in Output.txt

'''
#opening file Input in "w" mode
input_file = open("Input.txt","w")
input_file.write("Student Name , Sub1 , Sub2 , Sub3\n"
                  "Virat Kohli, 70, 56, 45\n"
                  "Suresh Raina, 80,28, 39\n"
                  "Yuvraj Singh, 69, 40,25\n"
                  "MS Dhoni,12, 15,17\n"
                  "Rohit Sharma,97,90,79\n"
                  "Shikhar Dhawan,66, 90,90\n"
                  "Rahul Dravid, 40, 58, 59\n"
)
input_file.close()
'''
#opening file Input in "r" mode and Output in "w" mode
input_file = open("Input.txt","r")
output_file = open("Output.txt","w")
count=0  #Will keep count of how much passed the exam
flag=0   #will act as counter cum flag which will say whether the student passed 
         #passed in all three subjects or not


for i in range(0,8):  #getting every data
  data =  input_file.readline()
  data1 = data.split(",")  #splitting data to get marks of student
  flag=0    #resetting flag for every student
  if data1[0] == "Student Name ": #checking if data contains the heading 
    continue

  else:
    for j in range(1,4):  #will check all three marks of students in this loop
      if int(data1[j])<=40: #if any one subject mark is less than 40 then he will fail
        break
      else:   
        flag+=1

  if flag==3:    #checking if a student cleared all three subjects or not
    count+=1     #if yes then include in list of passed  students
#writing data in file
output_file.write("Pass:"+str(count)+"\n"+"Fail:"+str(7-count)+"\n")
#closing the files
input_file.close()
output_file.close()

#this program complied and ran successfully

#Task - 9 Write all record in reverse order in output.txt


#opening file Input in "w" mode
input_file = open("Input.txt","w")
input_file.write("Student Name , Sub1 , Sub2 , Sub3\n"
                  "Virat Kohli, 70, 56, 45\n"
                  "Suresh Raina, 80,28, 39\n"
                  "Yuvraj Singh, 69, 40,25\n"
                  "MS Dhoni,12, 15,17\n"
                  "Rohit Sharma,97,90,79\n"
                  "Shikhar Dhawan,66, 90,90\n"
                  "Rahul Dravid, 40, 58, 59\n"
)
input_file.close()

#opening file Input in "r" mode and Output in "w" mode
input_file = open("Input.txt","r")
output_file = open("Output.txt","w")
data_f=''   #variaable which stores first line of file
data_r=''   #varaible which will store data of every student
data = input_file.read() #reading whole data from file

indicator = 0  #this variable will be used to store  first line of file
for i in data.split("\n"):  #separating the data 
  if indicator == 0:        #checking if indicator is 0 then storing first line in 'data_f' variable
    data_f = i
    indicator = indicator + 1  #making indicator 1 for indoicating that our work is done
  else:
    data_r = i + "\n" + data_r  #new data will be added above data stored in 'data_r' 
                                #leading to effect of reversing of data
output_file.write(data_f + data_r) #writing data in output file

#closing files
input_file.close()
output_file.close()

#this program complied and ran successfully