# -*- coding: utf-8 -*-
"""Stack using List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vl7q0PAjcXdIcmxTQmMa2_8EPEo7fb-g
"""

from google.colab import output
#Task: Implementation of stack using list
#Here in this program I have considered Top at last

SIZE = 7  #maximum size of stack
stack_data=0 #will contain data value
stack = []  #empty stack

#Menu for selecting an operation
print(" 1 -> Push(insert)")
print(" 2 -> Pop(delete)")
print(" 3 -> Peep")
print(" 4 -> Is Empty")
print(" 5 -> Is Full")
print(" 6 -> Empty Stack")
print(" 7 -> Total Elements")
print("If you want to exit press 8")      #exit info.
choice = int(input("Enter your choice:"))  #reading operation that needs to be performed

while choice > 0 and choice < 8:  #it will work till input is not in predefined range


  if choice == 1:                 #if user wants to insert an element
    output.clear()
    if len(stack)==SIZE:          #check whether the stack is full?
      print("Stack full!!.. please delete atleast one element.")  #if yes then no element can be inserted
      print("To insert new element,for that enter 2 from your keyboard.")

      print(" 1 -> Push(insert)")
      print(" 2 -> Pop(delete)")
      print(" 3 -> Peep")
      print(" 4 -> Is Empty")
      print(" 5 -> Is Full")
      print(" 6 -> Empty Stack")
      print(" 7 -> Total Elements")
      print("If you want to exit press 8")      #exit info.
      choice = int(input("Enter your choice:"))   #reading operation that needs to be performed

    else:
      stack_data = int(input("Enter your data:"))  #else we take the data of element to be inserted
      stack.append(stack_data)                     #insert element at the last of stack
      print(stack)                                 #printing stack after inserting new element
      print("\n")
     
      print(" 1 -> Push(insert)")
      print(" 2 -> Pop(delete)")
      print(" 3 -> Peep")
      print(" 4 -> Is Empty")
      print(" 5 -> Is Full")
      print(" 6 -> Empty Stack")
      print(" 7 -> Total Elements")
      print("If you want to exit press 8")      #exit info.
      choice = int(input("Enter your choice:"))    #reading operation that needs to be perfromed



  elif choice == 2:              #else if user wants to delete an element
    output.clear()
    if len(stack)==0:            #check whether the stack is empty?
      print("Stack empty!!, please insert atleast one element.")   #if yes then no element can be deleted
      print("To insert an element enter 1 from your keyboard")
      print(stack)
      print("\n")

      print(" 1 -> Push(insert)")
      print(" 2 -> Pop(delete)")
      print(" 3 -> Peep")
      print(" 4 -> Is Empty")
      print(" 5 -> Is Full")
      print(" 6 -> Empty Stack")
      print(" 7 -> Total Elements")
      print("If you want to exit press 8")      #exit info.
      choice = int(input("Enter your choice:"))   #reading operation that needs to be perfromed

    else:
      stack.pop()                                 #Deleting last element from the satck
      print(stack)                                #printing stack after poping is performed
      print("\n")

      print(" 1 -> Push(insert)")
      print(" 2 -> Pop(delete)")
      print(" 3 -> Peep")
      print(" 4 -> Is Empty")
      print(" 5 -> Is Full")
      print(" 6 -> Empty Stack")
      print(" 7 -> Total Elements")
      print("If you want to exit press 8")      #exit info.
      choice = int(input("Enter your choice:"))   #check whether the stack is empty?


  elif choice==3:                                 #else if user wants to know T.O.S
    output.clear()
    length = len(stack)                           
    print(stack[length-1])                        #printing the last value which will be our Top in this case
    print("\n")

    print(" 1 -> Push(insert)")
    print(" 2 -> Pop(delete)")
    print(" 3 -> Peep")
    print(" 4 -> Is Empty")
    print(" 5 -> Is Full")
    print(" 6 -> Empty Stack")
    print(" 7 -> Total Elements")
    print("If you want to exit press 8")      #exit info.
    choice = int(input("Enter your choice:"))     #reading operation that needs to be perfromed


  elif choice == 4:                              #else if user wants to know whether stack is empty or not
    output.clear()
    if len(stack)==0:                            #if length is zero then stack is empty

      print("Yes the stack is empty") 
      print("\n")

      print(" 1 -> Push(insert)")
      print(" 2 -> Pop(delete)")
      print(" 3 -> Peep")
      print(" 4 -> Is Empty")
      print(" 5 -> Is Full")
      print(" 6 -> Empty Stack")
      print(" 7 -> Total Elements")
      print("If you want to exit press 8")      #exit info.     
      choice = int(input("Enter your choice:"))  #reading operation that needs to be perfromed 

    else:
      print("No the stack is not empty")         #else stack is not empty
      print("\n")

      print(" 1 -> Push(insert)")
      print(" 2 -> Pop(delete)")
      print(" 3 -> Peep")
      print(" 4 -> Is Empty")
      print(" 5 -> Is Full")
      print(" 6 -> Empty Stack")
      print(" 7 -> Total Elements")
      print("If you want to exit press 8")      #exit info.
      choice = int(input("Enter your choice:"))  #reading operation that needs to be perfromed 



  elif choice == 5:                              #else if user wants to know whether stack overflowed or not
    output.clear()
    if len(stack) == SIZE:                       #if length of stack reached maximum limit of size then it is full
      print("Yes the stack is full")
      print("\n")

      print(" 1 -> Push(insert)")
      print(" 2 -> Pop(delete)")
      print(" 3 -> Peep")
      print(" 4 -> Is Empty")
      print(" 5 -> Is Full")
      print(" 6 -> Empty Stack")
      print(" 7 -> Total Elements")
      print("If you want to exit press 8")      #exit info.
      choice = int(input("Enter your choice:"))  #reading operation that needs to be perfromed 

    else:
      print("No the stack is not full")          #else stack is not full
      print("\n")

      print(" 1 -> Push(insert)")
      print(" 2 -> Pop(delete)")
      print(" 3 -> Peep")
      print(" 4 -> Is Empty")
      print(" 5 -> Is Full")
      print(" 6 -> Empty Stack")
      print(" 7 -> Total Elements")
      print("If you want to exit press 8")      #exit info.
      choice = int(input("Enter your choice:"))  #reading operation that needs to be perfromed 


  elif choice == 6:                              #else if user wants to delete all elements
    output.clear()
    if len(stack) == 0:
      print("Stack is empty!..Please insert atleast one element, for that enter 1 from your keyboard") #check whethe the stack is empty
      print("\n")

      print(" 1 -> Push(insert)")
      print(" 2 -> Pop(delete)")
      print(" 3 -> Peep")
      print(" 4 -> Is Empty")
      print(" 5 -> Is Full")
      print(" 6 -> Empty Stack")
      print(" 7 -> Total Elements")
      print("If you want to exit press 8")      #exit info.
      choice = int(input("Enter your choice:"))  #if yes then allow user to perform new operation
    else:
      print(stack)
      for i in range(len(stack)):                #else delete all elements of stack               
        stack.pop()
        print(stack)

      print("\n")
      print(" 1 -> Push(insert)")
      print(" 2 -> Pop(delete)")
      print(" 3 -> Peep")
      print(" 4 -> Is Empty")
      print(" 5 -> Is Full")
      print(" 6 -> Empty Stack")
      print(" 7 -> Total Elements")
      print("If you want to exit press 8")      #exit info.
    choice = int(input("Enter your choice:"))   #reading operation that needs to be perfromed


  elif choice == 7:                             #else if user wants to know total number of elements in stack
    output.clear()
    print("Total elements present in stack are {}".format(len(stack)))    #printing len of stack as it will contain that many elements only
    print("\n")

    print(" 1 -> Push(insert)")
    print(" 2 -> Pop(delete)")
    print(" 3 -> Peep")
    print( " 4 -> Is Empty")
    print(" 5 -> Is Full")
    print(" 6 -> Empty Stack")
    print(" 7 -> Total Elements")
    print("If you want to exit press 8")      #exit info.
    choice = int(input("Enter your choice:"))   #reading operation that needs to be perfromed

  elif choice == 8 or choice<0 or choice>8:     #exit the program
    print("Thank you for using this program")    

#This program compiled and ran successfully

